spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/accounts-db
    username:
    password:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  jackson:
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true
server:
  port: 8088
  servlet:
    context-path: /accounts

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka