spring:
  datasource:
    platform: sqlserver
    url: jdbc:sqlserver://localhost:1433;databaseName=accounts-db;trustServerCertificate=true
    username: ${db-username}
    password: ${db-password}
    initialization-mode: always
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
server:
  port: 8088
  servlet:
    context-path: /

eureka:
  instance:
    preferIpAddress: true # Register with IP address in Local environment as DNS is not available for local environment
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    shutdown:
      enabled: true
    prometheus:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true


info:
  app:
    name: "accounts"
    description: "Prime Bank Accounts Application"
    version: "1.0.0"
