spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/accounts-db
    username: admin
    password:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  port: 8088
  servlet:
    context-path: /accounts

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka