spring:
  datasource:
    platform: sqlserver
    url: jdbc:sqlserver://localhost:1433;databaseName=accounts-db;trustServerCertificate=true
    initialization-mode: always
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8088
  servlet:
    context-path: /accounts

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka