spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts-db
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8088
  servlet:
    context-path: /accounts

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka